# Site settings
baseurl = "https://techtitans.us/"
languageCode = "en-us"
title = "Tech Titans FTC Team 12762"
theme = "stellar"

googleAnalytics = "" #put your google-analytics ID here

[params]
  [params.header]
    title = "Tech Titans"
    description = 'FTC Team 12762'
    image = "images/logo.svg"

  [[params.navigation]]
    name = "About"
    href = "#intro"

  [[params.navigation]]
    name = "Outreach"
    href = "#first"

  [[params.navigation]]
    name = "Sponsers"
    href = "#second"

  [[params.navigation]]
    name = "Mentors"
    href = "#cta"

  [[params.navigation]]
    name = "Process"
    href = "#cta"

  [params.intro]
    title = "Ipsum sed adipiscing"
    description = "Sed lorem ipsum dolor sit amet nullam consequat feugiat consequat magna adipiscing magna etiam amet veroeros. Lorem ipsum dolor tempus sit cursus. Tempus nisl et nullam lorem ipsum dolor sit amet aliquam."
    image = "images/pic01.jpg"
    [[params.intro.action]]
      buttontext = "Learn More"
      href = "generic.html"


  [[params.section]]
    id = "first"
    title = "Magna veroeros"
    description = ""
    
    # the picture is storead at static/images/
    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "Ipsum consequat"
        description = "Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat."
        icon = "fa-code"

      [[params.section.feature]]
        title = "Amed sed feugiat"
        description = "Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat."
        icon = "fa-copy"

      [[params.section.feature]]
        title = "Dolor nullam"
        description = "Sed lorem amet ipsum dolor et amet nullam consequat a feugiat consequat tempus veroeros sed consequat."
        icon = "fa-diamond"
    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [[params.section]]
    id = "second"
    title = "Ipsum consequat"
    description = "Donec imperdiet consequat consequat. Suspendisse feugiat congue posuere. Nulla massa urna, fermentum eget quam aliquet."

    [params.section.statistics]
      enable = true
      [[params.section.statistic]]
        icon = "fa-code-fork"
        value = "5,120"
        text = "Etiam"
      [[params.section.statistic]]
        icon = "fa-folder-open-o"
        value = "8,192"
        text = "Magna"
      [[params.section.statistic]]
        icon = "fa-signal"
        value = "2,048"
        text = "Tempus"
      [[params.section.statistic]]
        icon = "fa-laptop"
        value = "4,096"
        text = "Aliquam"
      [[params.section.statistic]]
        icon = "fa-diamond"
        value = "1,024"
        text = "Nullam"

    [params.section.content]
      enable = true
      text = "Nam elementum nisl et mi a commodo porttitor. Morbi sit amet nisl eu arcu faucibus hendrerit vel a risus. Nam a orci mi, elementum ac arcu sit amet, fermentum pellentesque et purus. Integer maximus varius lorem, sed convallis diam accumsan sed. Etiam porttitor placerat sapien, sed eleifend a enim pulvinar faucibus semper quis ut arcu. Ut non nisl a mollis est efficitur vestibulum. Integer eget purus nec nulla mattis et accumsan ut magna libero. Morbi auctor iaculis porttitor. Sed ut magna ac risus et hendrerit scelerisque. Praesent eleifend lacus in lectus aliquam porta. Cras eu ornare dui curabitur lacinia."

    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"


  [[params.section]]
    id = "cta"
    title = "Congue imperdiet"
    description = "Donec imperdiet consequat consequat. Suspendisse feugiat congue posuere. Nulla massa urna, fermentum eget quam aliquet."
    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "Get Started"
        buttonUrl = "generic.html"
        customClass = "special"
      [[params.section.footer.action]]
        buttontext = "Learn More"
        buttonUrl = "generic.html"

  [params.footer]
    enable = true
    title = "Aliquam sed mauris"
    description = "Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio."

    email = "techtitans12762@gmail.com"

    [[params.footer.action]]
      href = "generic.html"
      buttontext = "Learn More"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://www.facebook.com/tyson.titans"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "https://www.instagram.com/titanstech.12762/"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "mailto:techtitans12762@gmail.com"

    # copyright
    [params.footer.copyright]
      enable = true
      text = "© 2018 Tech Titans"